const UNOCHA_str_to_alpha3 = {
  Afghanistan: "AFG",
  Albania: "ALB",
  Algeria: "DZA",
  Angola: "AGO",
  Argentina: "ARG",
  Armenia: "ARM",
  Azerbaijan: "AZE",
  Bangladesh: "BGD",
  Benin: "BEN",
  Bolivia: "BOL",
  "Bosnia and Herzegovina": "BIH",
  Botswana: "BWA",
  Brazil: "BRA",
  "Burkina Faso": "BFA",
  Burundi: "BDI",
  Cambodia: "KHM",
  Cameroon: "CMR",
  "Central African Republic": "CAF",
  Chad: "TCD",
  Chile: "CHL",
  Colombia: "COL",
  Congo: "COG",
  "Costa Rica": "CRI",
  "Côte d'Ivoire": "CIV",
  Cuba: "CUB",
  "Democratic Republic of the Congo": "COD",
  Djibouti: "DJI",
  "Dominican Republic": "DOM",
  Ecuador: "ECU",
  Egypt: "EGY",
  "El Salvador": "SLV",
  Eritrea: "ERI",
  Ethiopia: "ETH",
  Fiji: "FJI",
  Gambia: "GMB",
  Georgia: "GEO",
  Ghana: "GHA",
  Guatemala: "GTM",
  Guinea: "GIN",
  "Guinea-Bissau": "GNB",
  Haiti: "HTI",
  Honduras: "HND",
  India: "IND",
  Indonesia: "IDN",
  Iran: "IRN",
  Iraq: "IRQ",
  Jordan: "JOR",
  Kazakhstan: "KAZ",
  Kenya: "KEN",
  Kyrgyzstan: "KGZ",
  "Lao People's Democratic Republic": "LAO",
  Lebanon: "LBN",
  Lesotho: "LSO",
  Liberia: "LBR",
  Libya: "LBY",
  Madagascar: "MDG",
  Malawi: "MWI",
  Mali: "MLI",
  Mauritania: "MRT",
  Mexico: "MEX",
  Mongolia: "MNG",
  Morocco: "MAR",
  Mozambique: "MOZ",
  Myanmar: "MMR",
  Namibia: "NAM",
  Nepal: "NPL",
  Nicaragua: "NIC",
  Niger: "NER",
  Nigeria: "NGA",
  "North Korea": "PRK",
  Pakistan: "PAK",
  Palestine: "PSE",
  Panama: "PAN",
  "Papua New Guinea": "PNG",
  Paraguay: "PRY",
  Peru: "PER",
  Philippines: "PHL",
  Rwanda: "RWA",
  Senegal: "SEN",
  "Sierra Leone": "SLE",
  Somalia: "SOM",
  "South Sudan": "SSD",
  "Sri Lanka": "LKA",
  Sudan: "SDN",
  Syria: "SYR",
  Tajikistan: "TJK",
  Tanzania: "TZA",
  Thailand: "THA",
  "Timor-Leste": "TLS",
  Togo: "TGO",
  Tunisia: "TUN",
  Turkey: "TUR",
  Turkmenistan: "TKM",
  Uganda: "UGA",
  Ukraine: "UKR",
  Uzbekistan: "UZB",
  Venezuela: "VEN",
  "Viet Nam": "VNM",
  Yemen: "YEM",
  Zambia: "ZMB",
  Zimbabwe: "ZWE",
};

const UNOCHA_alpha3_to_str = {
  AFG: "Afghanistan",
  ALB: "Albania",
  DZA: "Algeria",
  AGO: "Angola",
  ARG: "Argentina",
  ARM: "Armenia",
  AZE: "Azerbaijan",
  BGD: "Bangladesh",
  BEN: "Benin",
  BOL: "Bolivia",
  BIH: "Bosnia and Herzegovina",
  BWA: "Botswana",
  BRA: "Brazil",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  KHM: "Cambodia",
  CMR: "Cameroon",
  CAF: "Central African Republic",
  TCD: "Chad",
  CHL: "Chile",
  COL: "Colombia",
  COG: "Congo",
  CRI: "Costa Rica",
  CIV: "Côte d'Ivoire",
  CUB: "Cuba",
  COD: "Democratic Republic of the Congo",
  DJI: "Djibouti",
  DOM: "Dominican Republic",
  ECU: "Ecuador",
  EGY: "Egypt",
  SLV: "El Salvador",
  ERI: "Eritrea",
  ETH: "Ethiopia",
  FJI: "Fiji",
  GMB: "Gambia",
  GEO: "Georgia",
  GHA: "Ghana",
  GTM: "Guatemala",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  HTI: "Haiti",
  HND: "Honduras",
  IND: "India",
  IDN: "Indonesia",
  IRN: "Iran",
  IRQ: "Iraq",
  JOR: "Jordan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KGZ: "Kyrgyzstan",
  LAO: "Lao People's Democratic Republic",
  LBN: "Lebanon",
  LSO: "Lesotho",
  LBR: "Liberia",
  LBY: "Libya",
  MDG: "Madagascar",
  MWI: "Malawi",
  MLI: "Mali",
  MRT: "Mauritania",
  MEX: "Mexico",
  MNG: "Mongolia",
  MAR: "Morocco",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  NAM: "Namibia",
  NPL: "Nepal",
  NIC: "Nicaragua",
  NER: "Niger",
  NGA: "Nigeria",
  PRK: "North Korea",
  PAK: "Pakistan",
  PSE: "Palestine",
  PAN: "Panama",
  PNG: "Papua New Guinea",
  PRY: "Paraguay",
  PER: "Peru",
  PHL: "Philippines",
  RWA: "Rwanda",
  SEN: "Senegal",
  SLE: "Sierra Leone",
  SOM: "Somalia",
  SSD: "South Sudan",
  LKA: "Sri Lanka",
  SDN: "Sudan",
  SYR: "Syria",
  TJK: "Tajikistan",
  TZA: "Tanzania",
  THA: "Thailand",
  TLS: "Timor-Leste",
  TGO: "Togo",
  TUN: "Tunisia",
  TUR: "Turkey",
  TKM: "Turkmenistan",
  UGA: "Uganda",
  UKR: "Ukraine",
  UZB: "Uzbekistan",
  VEN: "Venezuela",
  VNM: "Viet Nam",
  YEM: "Yemen",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
};

Object.freeze(UNOCHA_str_to_alpha3);
Object.freeze(UNOCHA_alpha3_to_str);

export { UNOCHA_str_to_alpha3, UNOCHA_alpha3_to_str };
